# Generated by Django 3.2.5 on 2021-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(upload_to='users/avatars', verbose_name='Фото профиля'),
        ),
    ]
