# Generated by Django 3.2.5 on 2022-01-29 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0003_alter_balance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='status',
            field=models.ForeignKey(default=uuid.UUID('510e9703-171c-46c9-8046-40e3d54a3224'), on_delete=django.db.models.deletion.CASCADE, to='app_loyalty.balancestatus'),
        ),
    ]
