# Generated by Django 3.2.5 on 2022-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_loyalty', '0004_alter_balance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Balance'),
        ),
    ]
