# Generated by Django 3.2.5 on 2021-07-24 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=1500, verbose_name='Заголовок')),
                ('decription', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.advertisementauthor', verbose_name='Владелец объявления')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.advertisementcategory', verbose_name='Категория объявления')),
                ('status', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.advertisementstatus', verbose_name='Статус объявления')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisements_app.advertisementtype', verbose_name='Тип объявления')),
            ],
        ),
    ]
