# Generated by Django 3.2.5 on 2021-07-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementcategory',
            name='name',
            field=models.CharField(choices=[(1, 'Авто'), (2, 'Недвижимость'), (3, 'Работа')], max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisementstatus',
            name='name',
            field=models.CharField(choices=[(1, 'Черновик'), (2, 'Опубликовано'), (3, 'Архив')], max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='name',
            field=models.CharField(choices=[(1, 'Продам'), (2, 'Куплю'), (3, 'Сдам')], max_length=100),
        ),
    ]
