# Generated by Django 3.2.5 on 2021-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0003_auto_20210724_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementcategory',
            name='name',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Недвижимость', 'Недвижимость'), ('Работа', 'Работа')], max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisementstatus',
            name='name',
            field=models.CharField(choices=[('Черновик', 'Черновик'), ('Опубликовано', 'Опубликовано'), ('Архив', 'Архив')], max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisementtype',
            name='name',
            field=models.CharField(choices=[('Продам', 'Продам'), ('Куплю', 'Куплю'), ('Сдам', 'Сдам')], max_length=100),
        ),
    ]
