# Generated by Django 3.2.5 on 2021-07-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0006_auto_20210724_1748'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements',
            table=None,
        ),
    ]
