# Generated by Django 3.2.5 on 2021-07-26 20:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0009_rename_decription_advertisements_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementauthor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
