# Generated by Django 3.2.5 on 2022-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_of_publication',
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(default=None, verbose_name='Year of Publication'),
        ),
    ]
