# Generated by Django 3.2.5 on 2022-01-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
