# Generated by Django 3.2.5 on 2022-02-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0006_auto_20220205_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='good',
        ),
        migrations.AddField(
            model_name='article',
            name='good',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_storage.good', verbose_name='Good name'),
            preserve_default=False,
        ),
    ]
