# Generated by Django 3.2.5 on 2021-11-11 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Store Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('building', models.CharField(max_length=150, verbose_name='Building')),
                ('office', models.CharField(default='Undefined', max_length=150, verbose_name='Office')),
                ('about', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Additional Information')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Item Title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(default=0, verbose_name='Item Price')),
                ('description', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Item Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.category', verbose_name='Category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.store', verbose_name='Store')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
