# Generated by Django 3.2.5 on 2021-09-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20210915_0407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_be_published', 'can_be_published'),), 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
