# Generated by Django 3.2.5 on 2021-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Флаг активности'),
        ),
    ]
