# Generated by Django 3.2.5 on 2021-09-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
