# Generated by Django 3.2.5 on 2021-09-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Может ли пользователь публиковать новости?')),
                ('news_count', models.IntegerField(default=0, verbose_name='Кол-во опубликованных новостей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
