# Generated by Django 3.2.5 on 2021-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('to_verify', 'to_verify'), ('to_moderator', 'to_moderator'))},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False, verbose_name='Является ли пользователь модератором?'),
        ),
    ]
