# Generated by Django 3.2.5 on 2021-11-11 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Offer Title')),
                ('subtitle', models.CharField(blank=True, default=None, max_length=600, null=True, verbose_name='Offer Subtitle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_special_offer', models.BooleanField(verbose_name='Is it a special offer?')),
                ('is_promo_event', models.BooleanField(verbose_name='Is it a promo event?')),
                ('store', models.ManyToManyField(to='app_catalog.Store', verbose_name='Store Name')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bonuses_used', models.FloatField(default=0, verbose_name='Amount of uses bonuses')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.item')),
                ('offer_used', models.ManyToManyField(blank=True, to='app_status.Offer', verbose_name='Name of used offer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_catalog.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bonus Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
            },
        ),
    ]
