# Generated by Django 3.2.5 on 2022-02-01 05:42

import app_storage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=app_storage.models.get_initial_order_status, on_delete=django.db.models.deletion.CASCADE, to='app_storage.orderstatus'),
        ),
    ]
