# Generated by Django 3.2.5 on 2022-02-05 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_storage', '0005_auto_20220202_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='good',
        ),
        migrations.RemoveField(
            model_name='good',
            name='price',
        ),
        migrations.RemoveField(
            model_name='good',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='good',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('good', models.ManyToManyField(to='app_storage.Good', verbose_name='Good name')),
                ('store', models.ManyToManyField(to='app_storage.Store', verbose_name='Store name')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_storage.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='article',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_storage.article'),
            preserve_default=False,
        ),
    ]
