# Generated by Django 3.2.5 on 2021-08-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20210729_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_news.news'),
        ),
    ]
